version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      - npm install
      - npm install -g serverless
  pre-build:
    commands:
      - npm lint
  build:
    commands:
      - npm test
  post-build:
    commands:
      - serverless deploy
