service: collie-api

provider:
  name: aws
  runtime: nodejs12.x
  region: us-east-1

functions:
  graphql:
    handler: src/index.handler
    events:
      - http:
          path: api
          method: post
          cors: true
      - http:
          path: api
          method: get
          cors: true
package:
  exclude:
    - __test__/**
    - src/local-server.js
    - package.json
    - package-lock.json
