service: collie-api

custom:
  stage: ${opt:stage, self:provider.stage}

provider:
  name: aws
  runtime: nodejs12.x
  region: us-east-1
  environment:
    DB_HOST: ${env:DB_HOST, file(vars/${self:custom.stage}.yml):DB_HOST}
    DB_USER: ${env:DB_USER, file(vars/${self:custom.stage}.yml):DB_USER}
    DB_PWD: ${env:DB_PWD, file(vars/${self:custom.stage}.yml):DB_PWD}
    DB_NAME: ${env:DB_NAME, file(vars/${self:custom.stage}.yml):DB_NAME}

functions:
  graphql:
    handler: src/index.handler
    events:
      - http:
          path: api
          method: post
          cors: true
      - http:
          path: api
          method: get
          cors: true
package:
  exclude:
    - __test__/**
    - src/local-server.js
    - package.json
    - package-lock.json
